moonWorldName: "moon"
earthWorldName: "world"

toTheMoon: "Mission Accomplished...! Traveling to the Moon"
toTheEarth: "Mission Accomplished...! Traveling back to Earth"

missionFailed: "Mission Failed...! You didn't get to Y 120"

useGravity: true
useEffects: true
useParticles: true

useGlassHelmets: true
useSkullHelmets: true

useRockets: true

useOxygenSafeZone: true

useCustomMobs: true
useSpecialMobs: true

useCustomBlockDrops: true
useCustomBlockNames: true
useCustomBlockLore: true

CustomBlockLore: "&7Moon Generator - Block"
MoonRockName: "Moon Rock"
SoftMoonRockName: "Soft Moon Rock"
MoonCobblestoneName: "Moon Cobblestone"

LostAstronautName: "Lost Astronaut"
MoonPhantomName: "Tamed Moon Phantom"
LostMoonExplorerName: "Lost Moon Explorer"
FailedExperimentalHorseName: "Failed Experimental Horse"
evolvedMoonCreeperName: "EVOLVED MOON CREEPER"

MoonMobSufixName: "Moon "
MoonMobPrefixName: ""